//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskMeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseDetail
    {
        public int ResponseId { get; set; }
        public int UserId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> Upvote { get; set; }
        public string Response { get; set; }
    
        public virtual QuestionDetail QuestionDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
